#!/usr/bin/env python3
"""Generate kernel/font.inc: 8x16 bitmap font for ASCII 32..126 (free Aileron font)."""
from PIL import Image, ImageDraw, ImageFont

W, H = 8, 16
font = ImageFont.load_default(size=14)

print(f"; generated by scripts/genfont.py — 8x16 bitmap font, ASCII 0x20..0x7E")
print(f"font_glyphs equ 95")
print(f"font_data:")
for code in range(32, 127):
    img = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(img)
    ch = chr(code)
    # measure and center the glyph in the 8x16 cell
    bbox = d.textbbox((0, 0), ch, font=font)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    x = max(0, (W - tw) // 2 - bbox[0])
    y = max(0, (H - th) // 2 - bbox[1]) - 1
    d.text((x, y), ch, fill=255, font=font)
    px = img.load()
    rows = []
    for ry in range(H):
        b = 0
        for rx in range(W):
            if px[rx, ry] >= 128:
                b |= 0x80 >> rx
        rows.append(b)
    line = ", ".join(f"0x{b:02X}" for b in rows)
    comment = f" '{ch}'" if ch not in ("'", "\\") else f" {ch!r}"
    print(f"    db {line}    ;{comment}")
print("font_end:")
